Вторая отправка
SkorokhodovSemen/java-filmorate pull request #4
Opened 2023-10-27 16:35 UTC by SkorokhodovSemen

Поправлен файл gitIgnore

2023-10-28 10:38 UTC, VadimZharkov requested changes
Привет, хорошая работа.
Можно поулучшать, при наличии времени и желания)
Т.к. у обоих контроллеров одинаковая функциональнось по работе с сущностями модели, то можно выделить ее в базовый контроллер. Сущности модели тоже имеют общую часть - идентификатор, и можно сделать базовый класс, назвать например Entity.
В итоге базовый контроллер мог бы иметь такое определение

```
public abstract class Controller<T extends Entity> {
    поля и методы для сохранения, получения сущностей, мапа и генерация идентификатора
} 
```

2023-10-29 09:47 UTC, SkorokhodovSemen commented
Все сделал, теперь валятся тесты Postman из-за SuperBuilder
Буду искать причину

2023-10-29 10:29 UTC, SkorokhodovSemen commented
Сделал.
Я только рад, что есть моменты где можно сделать код лучше. Просто не хватает практики и мест где почитать теорию.
Спасибо за комментарии)

2023-10-29 17:30 UTC, VadimZharkov approved these changes
Сейчас супер!

2023-10-29 17:54 UTC, merged