Попытался сделать абстрактные классы
SkorokhodovSemen/java-filmorate pull request #5
Opened 2023-10-28 12:19 UTC by SkorokhodovSemen

Что-то получилось, но кажется я не понял зачем это все нужно... Я сделал отдельную ветку, чтобы прошлый код не потерять, надеюсь правильно получилось. 
Вопрос следующий - что еще нужно добавить?
И я теперь не понимаю, у меня с постманом все работает, но свои тесты не компилируются, потому что я раньше через билдер заполнял поля, но id ушел в класс родителя и билдер его не видит. Как теперь его добавить?

И еще, мне нужно заморочиться с абстрактным классом контроллера с валидацией чтобы в классах наследниках использовать super и не переопределять методы?

2023-10-28 12:20 UTC, SkorokhodovSemen commented
Вопросов больше, чем ответов, надеюсь ты мне подскажешь)

2023-10-28 13:44 UTC, VadimZharkov commented
> Что-то получилось, но кажется я не понял зачем это все нужно... Я сделал отдельную ветку, чтобы прошлый код не потерять, надеюсь правильно получилось. Вопрос следующий - что еще нужно добавить? И я теперь не понимаю, у меня с постманом все работает, но свои тесты не компилируются, потому что я раньше через билдер заполнял поля, но id ушел в класс родителя и билдер его не видит. Как теперь его добавить?
> 
> И еще, мне нужно заморочиться с абстрактным классом контроллера с валидацией чтобы в классах наследниках использовать super и не переопределять методы?

В ООП есть понятие наследования, оно служит в том числе для того чтобы избежать дублирование кода.
Если не получается, то можно переприслать первый вариант. Я предлагал сделать улучшение кода, это не замечание. Если студент с первого раза сделал хорошо (как у тебя), то значит у него есть потенциал на большее)
По поводу @Builder https://bjoernkw.com/2023/01/22/inheriting-properties-for-lombok-builders-and-jpa-entities/

2023-10-28 13:49 UTC, VadimZharkov requested changes
Пример, как можно реализовать, в наследниках реализуем валидацию(она отличается), все остальное поведение одинаковое
```
public abstract class AbstractController<T extends Entity> {
	private final HashMap<Long, T> storage = new HashMap<>();
	private long counter = 0L;

	public T create(final T data) {
		validate(data);
		data.setId(++counter);
		storage.put(data.getId(), data);
		return data;
	}

	public T update(final T data) {
		if (!storage.containsKey(data.getId())) {
			throw new ValidationException("Not found key: " + data.getId());
		}
		validate(data);
		storage.put(data.getId(), data);
		return data;
	}

	public List<T> getAll() {
		return new ArrayList<>(storage.values());
	}

	abstract void validate(T data);

}
```

2023-10-29 09:19 UTC, SkorokhodovSemen commented
Спасибо большое, буду разбираться)

2023-10-29 09:44 UTC, closed without merging