Первая отправка финального ТЗ 11 спринта
SkorokhodovSemen/java-filmorate pull request #8
Opened 2023-11-26 13:17 UTC by SkorokhodovSemen

Фух, было сложно, не знаю на сколько красиво получилось.
Надеюсь оценишь

2023-11-27 16:50 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmControllerDao.java
> +public class FilmControllerDao {
Dao лишний суффикс для названий классов. Имеет смысл только в пакете dao.

2023-11-27 16:55 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmControllerDao.java
> +    public List<Film> findAll() {
К методам контроллеров нужно добавить логирование

2023-11-27 16:59 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        mpa.setName(jdbcTemplate.queryForObject(sqlForMpa, String.class, mpa.getId()));
Доп запрос к БД нужно убрать, вместо него лучше добавить в SQL запрос JOIN

2023-11-27 17:02 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +                .queryForRowSet("select * from film_genre where id_film = ?", rs.getInt("film_id"));
Слишком много доп запросов в маппере. В идеале здесь их быть вообще не должно

2023-11-27 17:04 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +            for (Genre genre : film.getGenres()) {
Добавлять в цикле по одному запросу не есть хорошо для производительности.
Лучше воспользоваться пакетной вставкой. Посмотри и примени здесь jdbcTemplate.batchUpdate

2023-11-27 17:06 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        return jdbcTemplate.queryForObject(sql, this::makeFilm, film.getId());
Лишний запрос, в методе уже есть фильм который был сохранен в БД, его и можно вернуть, если это необходимо

2023-11-27 17:07 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        validFound(film.getId());
Осуществять проверку на наличие сущности в БД лучше в классе сервисов. В Storage не должно быть бизнес логики.

2023-11-27 17:08 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmGenreDbStorage.java
> +                .queryForRowSet("select * from film_genre where (id_film = ? and genre_id = ?)", idFilm, idGenre);
Про пакетную вставку см. коммент выше

2023-11-27 17:13 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate
Нужно одним запросом

2023-11-27 17:18 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/UserRelationshipDbStorage.java
> +        return userStorageDao.findById(idUser1);
А зачем здесь возвращать юзера? Задача методов в классах storage должна быть минимальна, в данном случае  сохранить связь в таблицу. Если нужна логика для получения пользователя, то ее нужно разместить в классе сервиса.

2023-11-28 08:55 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmControllerDao.java
> +public class FilmControllerDao {
Убрал

2023-11-28 09:25 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        mpa.setName(jdbcTemplate.queryForObject(sqlForMpa, String.class, mpa.getId()));
Буду знать, что к бд лишний раз не обращаться, буду оптимизировать

2023-11-28 09:55 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        return jdbcTemplate.queryForObject(sql, this::makeFilm, film.getId());
Да решил возвращать id и выполнять поиск через findById

2023-11-28 11:08 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +                .queryForRowSet("select * from film_genre where id_film = ?", rs.getInt("film_id"));
Уменьшил до 1... Если подскажешь куда убрать на совсем - сделаю

2023-11-28 11:12 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        validFound(film.getId());
Я причем оставил валидацию в сервисе, просто не убрал из хранилища

2023-11-28 11:20 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmGenreDbStorage.java
> +                .queryForRowSet("select * from film_genre where (id_film = ? and genre_id = ?)", idFilm, idGenre);
Готово

2023-11-28 11:24 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate
Я уже осознал, как надо))

2023-11-28 11:41 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/UserRelationshipDbStorage.java
> +        return userStorageDao.findById(idUser1);
сделал методы void, посмотрел что в тестах не обязательно возвращать User

2023-11-28 12:27 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/UserRelationshipDbStorage.java
> +                .map(userStorageDao::findById)
Разобрался вроде с мапой для query for list

2023-11-28 13:50 UTC, SkorokhodovSemen commented
Было бы меньше коммитов, если бы остались бесплатные проверки в постмане)

2023-11-29 06:35 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +            jdbcTemplate.batchUpdate("insert into film_genre (id_film, genre_id) values (?, ?)",
Вроде как полностью дублируется с кодом со строки 90. Вынеси этот код в отдельный метод, например saveFilmGenres(Int filmId, List<Genre> genres)

2023-11-29 06:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmDbStorage.java
> +        List<Map<String, Object>> result = jdbcTemplate.queryForList(sql, rs.getInt("film_id"));
Если в фильме заполнять жанры то без запроса жанров на каждый фильм не обойтись. Это с точки зрения логики. Но если бизнес логика позволяет, то можно жанры не заполнять здесь, а запрашивать где-нибудь в классах сервисов, тогда когда они реально понадобятся. В общем если тесты пропускают, то лучше убрать заполнение жанров здесь.
Вот пример из референсного решения
```
	static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
		return new Film(
				rs.getLong("film_id"),
				rs.getString("FILMS.name"),
				rs.getString("description"),
				toLocalDate(rs.getDate("release_date")),
				rs.getLong("duration"),
				rs.getLong("rate"),
				new Mpa(rs.getLong("MPA.mpa_id"), rs.getString("MPA.name")));
	} 
```

2023-11-29 06:53 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        return idList.stream().map(filmStorageDao::findById).sorted((f1, f2) -> {
Вот здесь в цикле (stream) запросы к БД. СУБД же все уже за тебя сделала - order by rate desc. Все уже вернется в отсортированном виде и stream не нужен

2023-11-29 07:03 UTC, VadimZharkov requested changes
Можно еще улучшить)

2023-11-29 09:44 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        return filmStorageDao.findById(idFilm);
Просто опыта нет, а особо в ТЗ не написано, что возвращать надо, а что не надо
Наставник говорил, что пример хорошего тона - возвращать сущность с которой работаешь :\ Вот я и возвращал)

2023-11-29 10:30 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        return idList.stream().map(filmStorageDao::findById).sorted((f1, f2) -> {
Принял, просто сразу как-то не дошло, что здесь по-другому можно сделать

2023-11-29 10:32 UTC, SkorokhodovSemen commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        return filmStorageDao.findById(idFilm);
Да и в тестах, сначала поле genre нет, потом добавляется, в методе GetAll все равно придется добавить и без них не обойтись.

2023-11-29 11:00 UTC, SkorokhodovSemen commented
В принципе то я уловил смысл как правильно делать, но не понятки с тестами, когда и где они хотят что-то увидеть)

2023-11-29 11:55 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dbstorage/FilmLikesDbStorage.java
> +        return filmStorageDao.findById(idFilm);
> Просто опыта нет, а особо в ТЗ не написано, что возвращать надо, а что не надо Наставник говорил, что пример хорошего тона - возвращать сущность с которой работаешь :\ Вот я и возвращал)

Это да тоже верно, но если для этого нужен доп запрос, то уже не верно с точки зрения производительности.

2023-11-29 11:56 UTC, VadimZharkov approved these changes

2023-11-29 12:59 UTC, merged